# Generated by Django 3.2.15 on 2022-10-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserHash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('ChairLampResult', models.CharField(max_length=750)),
            ],
        ),
    ]
