# Generated by Django 3.2.15 on 2022-10-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeToGiveApp', '0002_auto_20221001_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairlamp',
            old_name='CorrectIndices',
            new_name='correct_indices',
        ),
        migrations.RenameField(
            model_name='chairlamp',
            old_name='ChairLampResult',
            new_name='results',
        ),
        migrations.RenameField(
            model_name='chairlamp',
            old_name='UserHash',
            new_name='user_hash',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserHash',
            new_name='user_hash',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='user_name',
        ),
    ]
