# Generated by Django 3.2.15 on 2022-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeToGiveApp', '0003_auto_20221001_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourdon',
            fields=[
                ('user_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('correct_indices', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('results', models.CharField(blank=True, default=None, max_length=750, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToulousePieron',
            fields=[
                ('user_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('correct_indices', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('results', models.CharField(blank=True, default=None, max_length=750, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chairlamp',
            name='correct_indices',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
