# Generated by Django 3.2.15 on 2022-10-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeToGiveApp', '0004_auto_20221003_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
