# Generated by Django 3.2.15 on 2022-10-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeToGiveApp', '0005_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
